<template>
	<Modal :show="show" title="Import process from external source" @closed="$emit('closed')" :submitFunction="submit">
		<template #default>
			<div class="content">
				You can load an external process from multiple different sources:
				<h3>Upload JSON file from your computer</h3>
				<form @submit.prevent.stop="uploadFile">
					<input type="file" name="file" @change="setFile" accept="application/json" /> <button :disabled="!hasFile">Upload</button>
				</form>
				<h3>Download JSON file from the internet</h3>
				<form @submit.prevent.stop="loadUrl">
					<input type="url" name="url" v-model="url" /> <button :disabled="!hasUrl">Load</button>
				</form>
				<template v-if="gh.length > 0">
					<h3>Examples from openEO processes repository</h3>
					<!-- ToDo: Show multiselect component instead -->
					<ul>
						<li v-for="file in gh" :key="file.name"><a @click="request(file.url)">{{ file.name }}</a></li>
					</ul>
				</template>
				<h3>Import from client libraries (Python and R)</h3>
				<p>
					You can also import processes generated by the Python and R client.<br />
					Please read the chapter "<a href="https://openeo.org/documentation/1.0/cookbook/#output-process-as-json" target="_blank">Output: Process as JSON</a>" in the openEO cookbook.<br />
					After storing the JSON file to your computer, you can upload the JSON file above.
				</p>
			</div>
		</template>
		<template #footer>
			<div class="footer">
				<button type="submit" :disabled="!process">
					Import
					<template v-if="processId === null">unnamed process</template>
					<code v-else-if="processId">{{ processId }}</code>
				</button>
			</div>
		</template>
	</Modal>
</template>

<script>
import Utils from '../../utils';
import Modal from './Modal.vue';

export default {
	name: 'ImportProcessModal',
	components: {
		Modal
	},
	data() {
		return {
			gh: [],
			process: null,
			url: null,
			file: null,
			show: true
		};
	},
	async created() {
		if (this.$config.importCommunityExamples) {
			try {
				// Get folders from repo and find the processes folder
				let response = await Utils.axios().get('https://api.github.com/repos/Open-EO/openeo-community-examples/git/trees/main');
				let folder = response.data.tree.find(file => file.path === 'processes');
				if (folder) {
					// Get files in the folder
					let response2 = await Utils.axios.get(folder.url);
					this.gh = response2.data.tree
						.filter(file => file.path.endsWith('.json'))
						.map(file => ({
							name: file.path.substring(0, file.path.length-5),
							url: `https://raw.githubusercontent.com/Open-EO/openeo-community-examples/main/processes/${file.path}`
						}));
				}
			} catch(error) {
				console.warn(error);
			}
		}
	},
	computed: {
		processId() {
			if (Utils.isObject(this.process)) {
				if (this.process.id) {
					return this.process.id;
				}
				else {
					return null;
				}
			}
			return '';
		},
		hasUrl() {
			return Utils.isUrl(this.url);
		},
		hasFile() {
			return !!this.file;
		}
	},
	methods: {
		checkProcess(data) {
			if (typeof data === 'string') {
				try {
					data = JSON.parse(data);
				} catch(error) {
					throw new Error('Process is not valid JSON');
				}
			}
			if (!Utils.isObject(data)) {
				throw new Error('Process does not contain any data');
			}
			if (!Utils.isObject(data.process_graph)) {
				throw new Error('Process does not contain a process graph');
			}
			return data;
		},
		setFile(event) {
			if (event.dataTransfer && event.dataTransfer.files && event.dataTransfer.files.length > 0) {
				this.file = event.dataTransfer.files[0];
			}
			else if (event.target && event.target.files && event.target.files.length > 0){
				this.file = event.target.files[0];
			}
			else {
				this.file = null;
			}
		},
		uploadFile() {
			var reader = new FileReader();
			reader.onload = async e => {
				try {
					this.process = this.checkProcess(e.target.result);
				} catch(error) {
					Utils.exception(this, error, "Upload failed");
				}
			};
			reader.onerror = error => Utils.exception(this, error, "Reading JSON file failed");
			reader.readAsText(this.file, "UTF-8");
		},
		loadUrl() {
			this.request(this.url);
		},
		async request(url) {
			try {
				if (!Utils.isUrl(url)) {
					throw new Error('Please provide a valid URL');
				}
				let response = await Utils.axios().get(url);
				this.process = this.checkProcess(response.data);
			} catch(error) {
				Utils.exception(this, error, "Download failed");
			}
		},
		submit() {
			if (!this.process) {
				return;
			}
			this.$emit('save', this.process);
			this.show = false;
		},
	}
}
</script>

<style scoped lang="scss">
h3 {
	margin-top: 1.5em;
	margin-bottom: 0.5em;
}
form {
	display: flex;
	input {
		flex-grow: 1;
	}
	button {
		min-width: 8em;
	}
}
</style>